package com.hw4_try2.demo.raccoon;

import jakarta.persistence.*;

@Entity
@Table(name = "raccoons")
public class Raccoon {

    //attributes, test with one nullable
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int raccoonId;

    @Column(nullable = false)
    private String name;

    @Column(nullable = false)
    private String species;

    @Column(nullable = false)
    private double size;

    private double weight;

    //constructor with id (assigned id?)
    public Raccoon(int raccoonId, String name, String species, double size, double weight) {
        this.raccoonId = raccoonId;
        this.name = name;
        this.species = species;
        this.size = size;
        this.weight = weight;
    }

    //constructor no id, generated by table with unique id
    public Raccoon(String name, String species, double size, double weight) {
        this.name = name;
        this.species = species;
        this.size = size;
        this.weight = weight;
    }

    //no-args constructor
    public Raccoon() {
    }

    //return attribute info
    public int getRaccoonId() {
        return raccoonId;
    }

    public void setRaccoonId(int raccoonId) {
        this.raccoonId = raccoonId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSpecies() {
        return species;
    }

    public void setSpecies(String species) {
        this.species = species;
    }

    public double getSize() {
        return size;
    }

    public void setSize(double size) {
        this.size = size;
    }

    public double getWeight() {
        return weight;
    }

    public void setWeight(double weight) {
        this.weight = weight;
    }
}

